import type { Metadata } from "next"
import "./globals.css"
import { Inter } from 'next/font/google'
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] }) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
